### ISSUE TITLE
Track

### ISSUE THREAD

**Issue by alkaid-007** [ByronDev121/DQN-Hind-Sight-Reward-Shaping#4]
could u share your Track File in AirSim？

**Comment by ByronDev121** [comment]
Hi alkaid-007,

This is not an issue but you can download the binaries [here](https://drive.google.com/drive/folders/1XVtIa9TgiqYlPzYfnBfOz236p_eVA1pw?usp=sharing) 

In the main working directory open a new terminal and run "./MyProject.exe NewTrack -windowed"

**Comment by alkaid-007** [comment]
thank u so much!
